import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/Home/NavigationBar";
import StoreProvider from './storeProvider';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* 
          TODO LIST - Aceternity
          - [✔️] Add dark mode
          - [➖] Background Beams
          - [➖] Background Gradient (Optional)
          - [➖] Bento Grid
          - [➖] Container Scroll Animation
          - [➖] Flip Words
          - [➖] Floating Navbar
          - [➖] Following Pointer
          - [➖] Github Globe
          - [➖] Glare Card
          - [➖] Gradient Animation
          - [➖] Google Gemini Effect
          - [➖] Hover Border Gradient
          - [➖] Mackbook Scroll (Optional)
          - [➖] Meteors
          - [➖] Placeholders And Vanish Input
          - [➖] Spotlight
          - [➖] Vortex
        */}
        <StoreProvider>
          <NavigationBar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
